# Generated by Django 6.0 on 2025-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=35)),
                ('Restaurant_Location', models.TextField(max_length=150)),
                ('Rating', models.IntegerField(max_length=1)),
                ('Image', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
