# Generated by Django 6.0 on 2025-12-31 06:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='Mobile_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000 000 0000', max_length=10, region=None),
        ),
    ]
