# Generated by Django 6.0 on 2025-12-31 06:07

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_restaurants_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='Mobile_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000 000 0000', max_length=13, region=None),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Rating',
            field=models.IntegerField(max_length=3),
        ),
    ]
