# Generated by Django 6.0 on 2025-12-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_alter_restaurants_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='Rating',
            field=models.IntegerField(),
        ),
    ]
