# Generated by Django 6.0 on 2026-01-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0004_alter_restaurants_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='Image',
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='Rating',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
