# Generated by Django 6.0 on 2026-01-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0005_remove_restaurants_image_alter_restaurants_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
