# Generated by Django 6.0 on 2026-01-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0006_restaurants_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='Restaurant_Location',
            field=models.TextField(max_length=250),
        ),
    ]
