# Generated by Django 6.0 on 2026-01-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0007_alter_restaurants_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='Url_Offical',
            field=models.URLField(blank=True, null=True),
        ),
    ]
