# Generated by Django 6.0 on 2025-12-31 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurants', '0003_alter_restaurants_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='Restaurants.restaurants')),
            ],
        ),
    ]
