# Generated by Django 6.0 on 2025-12-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='category',
            field=models.CharField(default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='dishes',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
