# Generated by Django 6.0 on 2026-01-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0002_dishes_category_dishes_image_dishes_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
