# Generated by Django 6.0 on 2026-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0003_alter_dishes_image'),
        ('Restaurants', '0007_alter_restaurants_restaurant_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='dishes',
            name='restaurants',
            field=models.ManyToManyField(related_name='dishes', to='Restaurants.restaurants'),
        ),
    ]
