# Generated by Django 6.0 on 2026-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0004_remove_dishes_restaurants_dishes_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='image',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
