# Generated by Django 6.0 on 2026-01-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0005_remove_dishes_image_alter_dishes_price'),
        ('Restaurants', '0007_alter_restaurants_restaurant_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='category',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='dishes',
            name='restaurants',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='Restaurants.restaurants'),
            preserve_default=False,
        ),
    ]
