# Generated by Django 6.0 on 2026-02-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0006_remove_dishes_category_alter_dishes_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
