# Generated by Django 6.0.2 on 2026-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0007_alter_dishes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
