# Generated by Django 6.0.2 on 2026-02-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0008_alter_dishes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
