# Generated by Django 6.0.2 on 2026-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0009_restaurant_alter_dishes_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='dishes',
            name='restaurant_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
