# Generated by Django 6.0.2 on 2026-02-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0010_delete_restaurant_dishes_restaurant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='restaurant_name',
        ),
    ]
