# Generated by Django 6.0.2 on 2026-02-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0011_restaurant_remove_dishes_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
