# Generated by Django 6.0.2 on 2026-02-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0012_remove_restaurant_restaurant_name_restaurant_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
