# Generated by Django 6.0.2 on 2026-02-24 09:14

import Restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0013_delete_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='Available_in',
            field=models.CharField(default=2, verbose_name=Restaurants.models.Restaurants),
            preserve_default=False,
        ),
    ]
