# Generated by Django 6.0.2 on 2026-02-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0014_dishes_available_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='Available_in',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
