# Generated by Django 6.0 on 2026-01-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_cart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='name',
        ),
    ]
